module.exports = [
    {
        calories: 530,
        fat: 20,
        carbohydrates: 42,
        protein: 44,
        sodium: 760,
        ingredients: "Chicken Breast, Water, Yellow Sweet Corn, Long Grain Brown Rice, Sour Cream (Cultured Cream), Black Beans, Shredded Cheddar Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes, Annatto Vegetable Color, Anti-Caking Agent (Potato Starch, Powdered Cellulose, Corn Starch), Natamycin (A Natural Mold Inhibitor)), Cilantro, Poblano Peppers, Red Bell Peppers, Red Onions, Green Onions, Olive Pomace Oil, Chili Powder (Chili Pepper, Spices (Including Mustard), Salt, Garlic Powder), Roasted Chicken Stock (Chicken Stock, Roasted Chicken Stock, Mirepoix Stock (Made Of Carrot, Celery And Onion Stocks, Dried Chicken Stock, Salt, Gelatin, Water, White Wine)), Jalapeño Peppers, Lime Juice Concentrate, Sea Salt, Cumin, Paprika (Paprika And Silicon Dioxide (Added To Make Free Flowing)), Black Pepper, Garlic, Granulated Garlic, Granulated Onion, Crushed Red Pepper Flakes, Dried Oregano\n",
        name: "Shredded Chicken Taco Bowl",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_800,q_auto,w_1336/everyplate_s3/image/645e87b278ea89b5870601a4-c7176d1e.jpg",
        prep_cook_time: 240
    },
    {
        calories: 710,
        fat: 54,
        carbohydrates: 16,
        protein: 43,
        sodium: 750,
        ingredients: "Chicken Breast, Green Beans, Riced Cauliflower, Unsalted Butter (Pasteurized Cream, Natural Flavorings), Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Avocado Oil Mayonnaise (Avocado Oil, Organic Certified Humane Free Range Egg Yolks, Water, Distilled Vinegar, Salt, Lime Juice Concentrate, Citric Acid, Lime Oil), Blanched Almond Flour, Almonds, Olive Pomace Oil, Garlic, Water, Grated Parmesan Cheese ((Parmesan Cheese (Pasteurized Cow’S Milk, Cheese Culture, Salt, Enzymes), Water, Milk Protein, Modified Food Starch, Palm Oil Blend, Salt, Disodium Phosphate, Citric Acid, Xanthan Gum), And Calcium Propionate (Preservative)), Shredded Parmesan Cheese (Parmesan Cheese (Pasteurized Part-Skim Milk, Cheese Culture, Salt, Enzymes), Powdered Cellulose To Prevent Caking, Natamycin (A Natural Mold Inhibitor)), Granulated Garlic, Sea Salt, Red Wine Vinegar, Black Pepper, Granulated Onion, Dried Parsley, Toasted Garlic Powder, Parsley, Toasted Garlic, Dried Basil, Lemon Powder (Citric Acid, Natural Lemon Flavor), Dried Chives, Granulated Green Onion, Dried Oregano, Dried Tarragon\n",
        name: "Herb-Crusted Chicken",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/645e652273dae28eab022fd7-e4272361.jpg",
        prep_cook_time: 180
    },
    {
        calories: 640,
        fat: 45,
        carbohydrates: 15,
        protein: 46,
        sodium: 900,
        ingredients: "Chorizo (Pork, Chorizo Seasoning (Spices, Salt, Paprika, Garlic & Onion Powders, Natural Flavoring), Water), Ground Beef, Ground Pork, Water, Sour Cream (Cultured Cream), Shredded Pepper Jack Cheese ((Pasteurized Milk, Hot Peppers (Jalapeño Peppers, Habanero Peppers), Cheese Culture, Salt, Enzymes), Potato Starch And Powdered Cellulose (Anti-Caking Agents) Natamycin (A Natural Mold Inhibitor)), Tomato Paste (Tomatoes, Citric Acid), Shredded Cheddar Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes, Annatto Vegetable Color, Anti-Caking Agent (Potato Starch, Powdered Cellulose, Corn Starch), Natamycin (A Natural Mold Inhibitor)), Green Bell Peppers, Tomato Sauce (Tomatoes, Tomato Puree (Water, Tomato Paste), Salt, Red Pepper, Dehydrated Bell Peppers, Dehydrated Onion, Dehydrated Garlic, Onion Powder, Garlic Powder, Spices, Spice Extractive, Citric Acid, Natural Flavoring), Yellow Bell Peppers, Onions, Green Onions, Garlic, Cilantro, Chili Powder (Chili Pepper, Spices (Including Mustard), Salt, Garlic Powder), Sea Salt, Ancho Chile Powder, Cumin\n",
        name: "Chorizo Chili",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/chorizo-chili-w22-a312d9a6.jpg",
        prep_cook_time: 210
    },
    {
        calories: 460,
        fat: 21,
        carbohydrates: 37,
        protein: 33,
        sodium: 660,
        ingredients: "Italian Herb Chicken Breast (Chicken, Water, Olive Oil, Red Wine Vinegar, Sea Salt, Dehydrated Garlic, Dehydrated Onion, Dehydrated Parsley, Italian Herb Seasoning (Rosemary Leaves, Oregano Leaves, Basil Leaves, Marjoram Leaves, Thyme) Black Pepper), Yukon Gold Potatoes, Yellow Sweet Corn, Zucchini, Leeks, Roasted Corn, Unsalted Butter (Pasteurized Cream, Natural Flavorings), Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Sour Cream (Cultured Cream), Whole Milk (Pasteurized Milk, Vitamin D3), Onions, Grated Parmesan Cheese ((Parmesan Cheese (Pasteurized Cow’S Milk, Cheese Culture, Salt, Enzymes), Water, Milk Protein, Modified Food Starch, Palm Oil Blend, Salt, Disodium Phosphate, Citric Acid, Xanthan Gum), And Calcium Propionate (Preservative)), Garlic, Olive Pomace Oil, Heavy Cream, Sea Salt, Leek Powder, Dried Chives, Granulated Garlic, Smoked Black Pepper (Pepper, Smoke Flavor), Italian Seasoning (Rosemary Leaves, Oregano Leaves, Basil Leaves, Marjoram Leaves, Thyme), Dried Parsley, Black Pepper\n",
        name: "Potato Leek Mash & Grilled Chicken",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/644c0eca1a2b8a8e3f0689f8-446660de.jpg",
        prep_cook_time: 120
    },
    {
        calories: 520,
        fat: 28,
        carbohydrates: 36,
        protein: 31,
        sodium: 830,
        ingredients: "Chicken Thighs, Green Beans, Water, Mushrooms, Long Grain And Wild Rice Blend (Long Grain Parboiled Rice (Enriched With Iron (Ferric Phosphate), Niacin, Thiamine, Mononitrate, Folic Acid), Wild Rice), Onions, Heavy Cream, Olive Pomace Oil, Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Garlic, Green Onions, Shredded Asiago Cheese (Pasteurized Cow’S Milk, Cheese Cultures, Salt, Enzymes, Natamycin (A Natural Mold Inhibitor)), Lemon Juice Concentrate, Roasted Garlic Oil (Olive Pomace Oil, Garlic), Mirepoix Concentrate (Water, Sea Salt, Vegetable Stock (Carrot, Celery And Onion Stocks), Carrot Stock, Tapioca Starch, Cabbage Juice Concentrate, Celery Stock, Onion Stock, Natural Flavors, Mushroom Stock, Tomato Paste), Sea Salt, Rubbed Sage, Black Pepper, Toasted Onion Powder, Granulated Garlic, Granulated Onion, Thyme, Rosemary, Dried Chives, Dried Dill Weed, Sage\n",
        name: "Mushroom Chicken Thighs & Wild Rice",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/642b23ffbd8807a7a6001f55-5c7a8dc0.jpg",
        prep_cook_time: 120
    },
    {
        calories: 490,
        fat: 26,
        carbohydrates: 42,
        protein: 23,
        sodium: 840,
        ingredients: "Broccoli, Cauliflower Cavatappi (Water, Cauliflower Powder, Potato Starch, Tapioca Starch, Whole Egg, Egg White, Xanthan Gum, Konjac, Salt), Ground Pork, Crushed Tomatoes (Tomatoes, Tomato Puree, Salt, Citric Acid, Ascorbic Acid), Roasted Garlic Oil (Olive Pomace Oil, Garlic), Garlic, Cabernet Sauvignon Wine (Grapes, Sulfites), Carrots, Celery, Onions, Tomato Paste (Tomatoes, Citric Acid), Roasted Chicken Stock (Chicken Stock, Roasted Chicken Stock, Mirepoix Stock (Made Of Carrot, Celery And Onion Stocks, Dried Chicken Stock, Salt, Gelatin, Water, White Wine)), Olive Pomace Oil, Basil, Sea Salt, Ground Fennel, Crushed Red Pepper Flakes\n",
        name: "Cavatappi & Italian-Style Pork Ragu",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/645e8ce680c408c5c302216c-5ed89456.jpg",
        prep_cook_time: 270
    },
    {
        calories: 560,
        fat: 31,
        carbohydrates: 33,
        protein: 39,
        sodium: 710,
        ingredients: "Beef Tenderloin, Carrots, Yukon Gold Potatoes, Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Unsalted Butter (Pasteurized Cream, Natural Flavorings), Sour Cream (Cultured Cream), Leeks, Whole Milk (Pasteurized Milk, Vitamin D3), Olive Pomace Oil, Heavy Cream, Sea Salt, Leek Powder, Rosemary, White Truffle Oil (Pure Olive Oil, Artificial And Natural Flavor), Garlic, Granulated Garlic, Dried Chives, Green Onions, Smoked Black Pepper (Pepper, Smoke Flavor), Black Pepper, Dried Parsley\n",
        name: "Truffle Butter Filet Mignon",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/6450037d8c92dd40c0023fff-eb8d4de6.jpg",
        prep_cook_time: 180
    },
    {
        calories: 620,
        fat: 32,
        carbohydrates: 36,
        protein: 50,
        sodium: 910,
        ingredients: "Beef Tenderloin, Russet Potatoes, Shrimp (Shrimp, Water, Salt), Zucchini, Yellow Squash, Red Bell Peppers, Green Bell Peppers, Olive Pomace Oil, Red Onions, Cilantro, Garlic, Jalapeño Peppers, Parsley, Apple Cider Vinegar, Onions, Leeks, Sea Salt, Black Pepper, Granulated Garlic, Granulated Onion, Green Onions, Rosemary, Thyme, Smoked Black Pepper (Pepper, Smoke Flavor), Lemon Juice Concentrate\n",
        name: "Chimichurri Filet Mignon & Shrimp",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/chimichurri-filet-mignon-shrimp-w17-4a222627.jpg",
        prep_cook_time: 210
    },
    {
        calories: 630,
        fat: 37,
        carbohydrates: 37,
        protein: 39,
        sodium: 850,
        ingredients: "Beef Chuck (Beef, Water, Sea Salt, Dehydrated Onion, Dehydrated Garlic), Yukon Gold Potatoes, Carrots, Green Peas, Light Sour Cream (Cultured Cream, Skim Milk), Sour Cream (Cultured Cream), Horseradish (Horseradish Roots, Distilled Vinegar, Salt), Unsalted Butter (Pasteurized Cream, Natural Flavorings), Whole Milk (Pasteurized Milk, Vitamin D3), Green Onions, Avocado Oil Mayonnaise (Avocado Oil, Organic Certified Humane Free Range Egg Yolks, Water, Distilled Vinegar, Salt, Lime Juice Concentrate, Citric Acid, Lime Oil), Olive Pomace Oil, Honey, Sea Salt, Toasted Garlic Powder, Garlic, Dried Onion Flakes, Toasted Onion Powder, Black Pepper, Rosemary, Ground Mustard Seed, Dried Chives, Toasted Garlic, White Pepper\n",
        name: "Horseradish Shredded Beef",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/649f03b91f082ea3565720e4-691d934b.jpeg",
        prep_cook_time: 120
    },
    {
        calories: 610,
        fat: 30,
        carbohydrates: 44,
        protein: 42,
        sodium: 860,
        ingredients: "Chicken Breast, Brown Rice Elbow Macaroni (Water, Brown Rice Flour, Potato Starch, Tapioca Starch, Whole Egg, Egg White, Xanthan Gum, Salt), Yellow Sweet Corn, Poblano Peppers, Water, Grape Tomatoes, Red Bell Peppers, Monterey Jack Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes, Anti-Caking Agents (Potato Starch, Powdered Cellulose), Natamycin (A Natural Mold Inhibitor)), Jalapeño Peppers, Heavy Cream, Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Onions, Whole Milk (Pasteurized Milk, Vitamin D3), Red Onions, Garlic, Olive Pomace Oil, Sea Salt, Black Pepper, Granulated Garlic, Cilantro, Cumin, Granulated Onion, Jalapeño Powder, Crushed Red Pepper Flakes\n",
        name: "Southwestern-Style Chicken Mac",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/645e981568d9e7fcf10e4048-b9be589e.jpg",
        prep_cook_time: 270
    },
    {
        calories: 670,
        fat: 49,
        carbohydrates: 17,
        protein: 46,
        sodium: 820,
        ingredients: "Beef Tenderloin, Broccolini, Cauliflower, Celery Root, Heavy Cream, Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Olive Pomace Oil, Bleu Cheese Crumbles ((Pasteurized Milk, Cheese Cultures, Salt, Enzymes), Penicillium Roqueforti, Powdered Cellulose To Prevent Caking, Natamycin (A Natural Mold Inhibitor)), Unsalted Butter (Pasteurized Cream, Natural Flavorings), Grated Parmesan Cheese ((Parmesan Cheese (Pasteurized Cow’S Milk, Cheese Culture, Salt, Enzymes), Water, Milk Protein, Modified Food Starch, Palm Oil Blend, Salt, Disodium Phosphate, Citric Acid, Xanthan Gum), And Calcium Propionate (Preservative)), Green Onions, Sea Salt, Dried Chives, Toasted Garlic, Smoked Black Pepper (Pepper, Smoke Flavor), Dried Onion Flakes, Toasted Onion Powder, Toasted Garlic Powder, Garlic, White Pepper, Rosemary, Lemon Juice Concentrate\n",
        name: "Blue Cheese Filet Mignon",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/blue-cheese-filet-mignon-w12-58f5aba4.jpg",
        prep_cook_time: 270
    },
    {
        calories: 560,
        fat: 43,
        carbohydrates: 13,
        protein: 33,
        sodium: 1200,
        ingredients: "Barramundi, Yellow Squash, Riced Cauliflower, Poblano Peppers, Water, Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Unsalted Butter (Pasteurized Cream, Natural Flavorings), Red Bell Peppers, Olive Pomace Oil, Grated Parmesan Cheese ((Parmesan Cheese (Pasteurized Cow’S Milk, Cheese Culture, Salt, Enzymes), Water, Milk Protein, Modified Food Starch, Palm Oil Blend, Salt, Disodium Phosphate, Citric Acid, Xanthan Gum), And Calcium Propionate (Preservative)), Cilantro, Green Onions, Sea Salt, Lime Juice Concentrate, Orange Juice, Toasted Garlic, Black Pepper, Cumin, Garlic, Gochugaru Chile Flakes, Granulated Garlic, Toasted Garlic Powder, Ancho Chile Powder, Jalapeño Powder, Dried Oregano, Italian Seasoning (Rosemary Leaves, Oregano Leaves, Basil Leaves, Marjoram Leaves, Thyme)\n",
        name: "Cilantro Lime Barramundi",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/649f08111f082ea356572132-a36fc34a.jpeg",
        prep_cook_time: 150
    },
    {
        calories: 570,
        fat: 32,
        carbohydrates: 24,
        protein: 42,
        sodium: 840,
        ingredients: "Pork Chop, Carrots, Red Potatoes, Artichoke Hearts (Artichoke Hearts, Water, Salt, Citric Acid And/Or Ascorbic Acid, Citric Acid), Water, Light Sour Cream (Cultured Cream, Skim Milk), Unsalted Butter (Pasteurized Cream, Natural Flavorings), Green Onions, Olive Pomace Oil, Neufchatel Cheese (Pasteurized Milk And Cream, Skim Milk, Cheese Culture, Salt, Guar Gum, Carob Bean Gum, Xanthan Gum), Shredded Parmesan Cheese (Parmesan Cheese (Pasteurized Part-Skim Milk, Cheese Culture, Salt, Enzymes), Powdered Cellulose To Prevent Caking, Natamycin (A Natural Mold Inhibitor)), Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Garlic, Louisiana Hot Sauce (Aged Peppers, Distilled Vinegar, Salt), Red Wine Vinegar, Granulated Garlic, Sea Salt, Toasted Onion Powder, Apple Cider Vinegar, Black Pepper, Rosemary, Roasted Chicken Stock (Chicken Stock, Roasted Chicken Stock, Mirepoix Stock (Made Of Carrot, Celery And Onion Stocks, Dried Chicken Stock, Salt, Gelatin, Water, White Wine)), Dried Parsley, Dried Chives, Xanthan Gum, Toasted Garlic Powder\n",
        name: "Artichoke & Parmesan Pork Chop",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/644c2c63a7d3a306fe07ae7d-13e94f2f.jpg",
        prep_cook_time: 300
    },
    {
        calories: 490,
        fat: 27,
        carbohydrates: 31,
        protein: 32,
        sodium: 670,
        ingredients: "Garlic Herb Chicken Breast (Chicken, Water, Olive Oil, Red Wine Vinegar, Sea Salt, Dehydrated Garlic, Dehydrated Onion, Dehydrated Parsley, Black Pepper), Red Potatoes, Broccoli, Unsalted Butter (Pasteurized Cream, Natural Flavorings), Water, Olive Pomace Oil, Honey, Grated Parmesan Cheese ((Parmesan Cheese (Pasteurized Cow’S Milk, Cheese Culture, Salt, Enzymes), Water, Milk Protein, Modified Food Starch, Palm Oil Blend, Salt, Disodium Phosphate, Citric Acid, Xanthan Gum), And Calcium Propionate (Preservative)), Parsley, Sea Salt, Granulated Garlic, Rosemary, Black Pepper, Leek Powder, Toasted Garlic Powder, Xanthan Gum, Dried Chives\n",
        name: "Honey Butter Grilled Chicken",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/649f06f11f082ea35657211e-71984d16.jpeg",
        prep_cook_time: 180
    },
    {
        calories: 440,
        fat: 21,
        carbohydrates: 29,
        protein: 33,
        sodium: 830,
        ingredients: "Salmon (Salmon, Color Added Via Feed (Astaxanthin)), Russet Potatoes, Water, Concentrated Crushed Tomatoes (Tomatoes, Salt, Citric Acid), Great Northern Beans (Great Northern Beans, Water, Salt, Calcium Chloride), Pearl Onions, Fire Roasted Diced Tomatoes (Tomatoes, Tomato Juice, Sea Salt, Calcium Chloride, Citric Acid), Garlic, Roasted Garlic Oil (Olive Pomace Oil, Garlic), Capers (Capers, Water, Vinegar, Salt), Parsley, Sea Salt, Rosemary, Tomato Powder (Tomato Powder, Silicon Dioxide (Anti-Caking Agent)), Olive Pomace Oil, Thyme, Toasted Garlic, Granulated Garlic, Dried Basil, Dried Oregano, Gochugaru Chile Flakes\n",
        name: "Tuscan Baked Salmon",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/649f070a0cb992f7059806a4-a56d280a.jpeg",
        prep_cook_time: 120
    },
    {
        calories: 630,
        fat: 46,
        carbohydrates: 11,
        protein: 43,
        sodium: 700,
        ingredients: "Chicken Breast, Riced Cauliflower, Heavy Cream, Neufchatel Cheese (Pasteurized Milk And Cream, Skim Milk, Cheese Culture, Salt, Guar Gum, Carob Bean Gum, Xanthan Gum), Water, Shredded Cheddar Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes, Annatto Vegetable Color, Anti-Caking Agent (Potato Starch, Powdered Cellulose, Corn Starch), Natamycin (A Natural Mold Inhibitor)), Olive Pomace Oil, Sliced Jalapeño Peppers (Jalapeño Peppers, Water, Salt, Vinegar, Calcium Chloride, Sodium Benzoate (Preservative), Riboflavin), Onions, Sour Cream (Cultured Cream), Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Green Onions, Jalapeño Peppers, Garlic, Whole Milk (Pasteurized Milk, Vitamin D3), Cilantro, Roasted Chicken Stock (Chicken Stock, Roasted Chicken Stock, Mirepoix Stock (Made Of Carrot, Celery And Onion Stocks, Dried Chicken Stock, Salt, Gelatin, Water, White Wine)), Lime Juice Concentrate, Sea Salt, Cumin, Coriander, Ancho Chile Powder, Dried Oregano, Black Pepper, Paprika (Paprika And Silicon Dioxide (Added To Make Free Flowing)), Smoked Paprika\n",
        name: "Jalapeño-Lime-Cheddar Chicken",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/645e7c9f73dae28eab022fec-2736a83d.jpg",
        prep_cook_time: 150
    },
    {
        calories: 590,
        fat: 43,
        carbohydrates: 15,
        protein: 35,
        sodium: 850,
        ingredients: "Chicken Breast, Zucchini, Water, Concentrated Crushed Tomatoes (Tomatoes, Salt, Citric Acid), Red Bell Peppers, Heavy Cream, Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Olive Pomace Oil, Unsalted Butter (Pasteurized Cream, Natural Flavorings), Grated Romano Cheese (Imported Romano (Sheep’S Milk, Cheese Culture, Salt, Enzymes), Powdered Cellulose (Anti-Caking Agent), And Calcium Propionate (Preservative)), Tomato Paste (Tomatoes, Citric Acid), Garlic, Onions, Fennel, Sea Salt, Grated Parmesan Cheese ((Parmesan Cheese (Pasteurized Cow’S Milk, Cheese Culture, Salt, Enzymes), Water, Milk Protein, Modified Food Starch, Palm Oil Blend, Salt, Disodium Phosphate, Citric Acid, Xanthan Gum), And Calcium Propionate (Preservative)), Italian Seasoning (Rosemary Leaves, Oregano Leaves, Basil Leaves, Marjoram Leaves, Thyme), Smoked Black Pepper (Pepper, Smoke Flavor), Roasted Chicken Stock (Chicken Stock, Roasted Chicken Stock, Mirepoix Stock (Made Of Carrot, Celery And Onion Stocks, Dried Chicken Stock, Salt, Gelatin, Water, White Wine)), Black Pepper, Granulated Garlic, White Pepper, Rosemary Powder, Dried Parsley\n",
        name: "Tomato & Romano Chicken",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/6458fe6175a38c4fa30b47c2-cac33470.jpg",
        prep_cook_time: 270
    },
    {
        calories: 560,
        fat: 43,
        carbohydrates: 12,
        protein: 33,
        sodium: 710,
        ingredients: "Garlic Herb Chicken Breast (Chicken, Water, Olive Oil, Red Wine Vinegar, Sea Salt, Dehydrated Garlic, Dehydrated Onion, Dehydrated Parsley, Black Pepper), Broccoli, Grape Tomatoes, Heavy Cream, Onions, Olive Pomace Oil, Unsalted Butter (Pasteurized Cream, Natural Flavorings), Garlic, Chardonnay Wine (Grapes, Sulfites), Grated Parmesan Cheese ((Parmesan Cheese (Pasteurized Cow’S Milk, Cheese Culture, Salt, Enzymes), Water, Milk Protein, Modified Food Starch, Palm Oil Blend, Salt, Disodium Phosphate, Citric Acid, Xanthan Gum), And Calcium Propionate (Preservative)), Blanched Almond Flour, Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Sea Salt, Basil, Lemon Powder (Citric Acid, Natural Lemon Flavor), Dried Parsley\n",
        name: "Creamy Parmesan Chicken",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/645e780dca5268a6f40060dc-1c1b614c.jpg",
        prep_cook_time: 180
    },
    {
        calories: 650,
        fat: 49,
        carbohydrates: 13,
        protein: 41,
        sodium: 870,
        ingredients: "Ground Beef, Riced Cauliflower, Whole Milk (Pasteurized Milk, Vitamin D3), Neufchatel Cheese (Pasteurized Milk And Cream, Skim Milk, Cheese Culture, Salt, Guar Gum, Carob Bean Gum, Xanthan Gum), Heavy Cream, Shredded Cheddar Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes, Annatto Vegetable Color, Anti-Caking Agent (Potato Starch, Powdered Cellulose, Corn Starch), Natamycin (A Natural Mold Inhibitor)), Monterey Jack Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes, Anti-Caking Agents (Potato Starch, Powdered Cellulose), Natamycin (A Natural Mold Inhibitor)), Diced Green Chiles (Green Chile Peppers, Water, Salt, Citric Acid, Calcium Chloride), Olive Pomace Oil, Concentrated Crushed Tomatoes (Tomatoes, Salt, Citric Acid), Onions, Chili Powder (Chili Pepper, Spices (Including Mustard), Salt, Garlic Powder), Unsalted Butter (Pasteurized Cream, Natural Flavorings), Paprika (Paprika And Silicon Dioxide (Added To Make Free Flowing)), Garlic, Cilantro, Granulated Garlic, Sea Salt, Water, Cayenne Pepper, Cumin\n",
        name: "Queso Fundido",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/644bf073e6395656d500d2ca-95a66d4f.jpg",
        prep_cook_time: 150
    },
    {
        calories: 670,
        fat: 49,
        carbohydrates: 11,
        protein: 45,
        sodium: 670,
        ingredients: "Pork Chop, Broccoli, Brussels Sprouts, Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Heavy Cream, Water, Olive Pomace Oil, Shredded White Cheddar Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes, Anti-Caking Agents (Potato Starch, Powdered Cellulose, Natamycin (A Natural Mold Inhibitor)), Shredded Smoked Gouda Cheese (Pasteurized Milk, Water, Cheese Cultures, Skim Milk, Salt, Enzymes, Sodium Phosphate, Calcium Propionate (Preservative), Apocarotenal (For Color)), And Powdered Cellulose (To Prevent Caking)), Poblano Peppers, Onions, Garlic, Whole Milk (Pasteurized Milk, Vitamin D3), Green Onions, Sea Salt, Black Pepper, Apple Cider Vinegar, Rubbed Sage, Dried Chives, Dried Parsley, Smoked Black Pepper (Pepper, Smoke Flavor)\n",
        name: "Black Pepper & Sage Pork Chop",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/645e7c01e243b48c3d09727f-41f8dc45.jpg",
        prep_cook_time: 300
    },
    {
        calories: 600,
        fat: 46,
        carbohydrates: 12,
        protein: 34,
        sodium: 920,
        ingredients: "Garlic Herb Chicken Breast (Chicken, Water, Olive Oil, Red Wine Vinegar, Sea Salt, Dehydrated Garlic, Dehydrated Onion, Dehydrated Parsley, Black Pepper), Zucchini, Mushrooms, Heavy Cream, Neufchatel Cheese (Pasteurized Milk And Cream, Skim Milk, Cheese Culture, Salt, Guar Gum, Carob Bean Gum, Xanthan Gum), Olive Pomace Oil, Onions, Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Unsalted Butter (Pasteurized Cream, Natural Flavorings), Dijon Mustard (Distilled Vinegar, Water, No. 1 Grade Mustard Seed, Salt, Chardonnay Wine, Citric Acid, Tartaric Acid, Spices, Turmeric), Whole Grain Mustard (Water, Mustard Seed, Distilled Vinegar, Salt, White Wine, Citric Acid, Tartaric Acid, Spices), Green Onions, Garlic, Sherry Wine (Grapes, Sulfites), Roasted Chicken Stock (Chicken Stock, Roasted Chicken Stock, Mirepoix Stock (Made Of Carrot, Celery And Onion Stocks, Dried Chicken Stock, Salt, Gelatin, Water, White Wine)), Blanched Almond Flour, Shredded Parmesan Cheese (Parmesan Cheese (Pasteurized Part-Skim Milk, Cheese Culture, Salt, Enzymes), Powdered Cellulose To Prevent Caking, Natamycin (A Natural Mold Inhibitor)), Dried Tarragon, Sea Salt, Rosemary, Smoked Black Pepper (Pepper, Smoke Flavor), Black Pepper\n",
        name: "Dijon Chicken & Roasted Mushrooms",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/649f027d0cb992f70598065b-048c4772.jpeg",
        prep_cook_time: 120
    },
    {
        calories: 680,
        fat: 49,
        carbohydrates: 17,
        protein: 44,
        sodium: 790,
        ingredients: "Pork Tenderloin, Broccoli, Mushrooms, Spinach, Concentrated Crushed Tomatoes (Tomatoes, Salt, Citric Acid), Water, Olive Pomace Oil, Heavy Cream, Neufchatel Cheese (Pasteurized Milk And Cream, Skim Milk, Cheese Culture, Salt, Guar Gum, Carob Bean Gum, Xanthan Gum), Unsalted Butter (Pasteurized Cream, Natural Flavorings), Onions, Grated Parmesan Cheese ((Parmesan Cheese (Pasteurized Cow’S Milk, Cheese Culture, Salt, Enzymes), Water, Milk Protein, Modified Food Starch, Palm Oil Blend, Salt, Disodium Phosphate, Citric Acid, Xanthan Gum), And Calcium Propionate (Preservative)), Walnuts, Cabernet Sauvignon Wine (Grapes, Sulfites), Garlic, Red Wine Vinegar, Tomato Paste (Tomatoes, Citric Acid), Basil, Toasted Onion Powder, Sea Salt, Green Onions, Toasted Garlic Powder, Thyme, Smoked Black Pepper (Pepper, Smoke Flavor), Black Pepper, Italian Seasoning (Rosemary Leaves, Oregano Leaves, Basil Leaves, Marjoram Leaves, Thyme), Dried Oregano, Crushed Red Pepper Flakes\n",
        name: "Creamy Tomato Pork Tenderloin",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/6442ecdd866a6fe3c0087b2e-cbf2d362.jpg",
        prep_cook_time: 270
    },
    {
        calories: 610,
        fat: 46,
        carbohydrates: 16,
        protein: 33,
        sodium: 930,
        ingredients: "Ground Beef, Zucchini, Riced Cauliflower, Sour Cream (Cultured Cream), Water, Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Onions, Shredded Sharp Cheddar Cheese (Pasteurized Milk, Cheese Culture, Salt, Enzymes, Annatto (Vegetable Color), Anti-Caking Blend (Potato Starch, Powdered Cellulose)), Heavy Cream, Olive Pomace Oil, Nitrite/Nitrate-Free Uncured Bacon (Pork, Water, Salt, Celery Powder, Cherry Baste Aid), Jalapeño Peppers, Granulated Onion, Garlic, Granulated Garlic, Sea Salt, Buttermilk Powder, Reduced Brown Stock ((Veal Bones, Water), Beef Stock, Mirepoix Stock (Made Of Carrot, Celery And Onion Stocks), Red Wine, Tomato Paste, Gelatin, Salt, Carrot Stock, Celery Stock)), Smoked Black Pepper (Pepper, Smoke Flavor), Black Pepper, Dried Dill Weed, Dried Chives, Dried Parsley\n",
        name: "Texas Cheddar Burger",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/texas-cheddar-burger-w37-c38fd64d.jpg",
        prep_cook_time: 210
    },
    {
        calories: 640,
        fat: 46,
        carbohydrates: 13,
        protein: 41,
        sodium: 890,
        ingredients: "Chicken Breast, Zucchini, Green Bell Peppers, Water, Shredded Cheddar Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes, Annatto Vegetable Color, Anti-Caking Agent (Potato Starch, Powdered Cellulose, Corn Starch), Natamycin (A Natural Mold Inhibitor)), Olive Pomace Oil, Red Bell Peppers, Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Whole Milk (Pasteurized Milk, Vitamin D3), Heavy Cream, Unsalted Butter (Pasteurized Cream, Natural Flavorings), Grated Parmesan Cheese ((Parmesan Cheese (Pasteurized Cow’S Milk, Cheese Culture, Salt, Enzymes), Water, Milk Protein, Modified Food Starch, Palm Oil Blend, Salt, Disodium Phosphate, Citric Acid, Xanthan Gum), And Calcium Propionate (Preservative)), Garlic, Tamari (Water, Soybeans, Salt, Alcohol (To Preserve Freshness)), Sea Salt, Toasted Garlic, Granulated Garlic, Black Pepper, Granulated Onion, Gochugaru Chile Flakes, Red Wine Vinegar, Italian Seasoning (Rosemary Leaves, Oregano Leaves, Basil Leaves, Marjoram Leaves, Thyme), Dried Parsley, Dried Chives, Paprika (Paprika And Silicon Dioxide (Added To Make Free Flowing)), Turmeric\n",
        name: "Cheesy Chicken & Peppers",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/643046eee323c7be6e00b477-086d4d8f.jpg",
        prep_cook_time: 120
    },
    {
        calories: 710,
        fat: 56,
        carbohydrates: 14,
        protein: 38,
        sodium: 870,
        ingredients: "Salmon (Salmon, Color Added Via Feed (Astaxanthin)), Spinach, Haricots Verts, Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Olive Pomace Oil, Onions, Unsalted Butter (Pasteurized Cream, Natural Flavorings), Shredded Parmesan Cheese (Parmesan Cheese (Pasteurized Part-Skim Milk, Cheese Culture, Salt, Enzymes), Powdered Cellulose To Prevent Caking, Natamycin (A Natural Mold Inhibitor)), Garlic, Almonds, Grated Parmesan Cheese ((Parmesan Cheese (Pasteurized Cow’S Milk, Cheese Culture, Salt, Enzymes), Water, Milk Protein, Modified Food Starch, Palm Oil Blend, Salt, Disodium Phosphate, Citric Acid, Xanthan Gum), And Calcium Propionate (Preservative)), Baby Kale, Basil, Spinach, Sun-Dried Tomatoes (Sun-Dried Tomatoes, Salt), Water, Sea Salt, Granulated Garlic\n",
        name: "Pesto Salmon",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/6459002375a38c4fa30b47c6-2071566c.jpg",
        prep_cook_time: 210
    },
    {
        calories: 420,
        fat: 21,
        carbohydrates: 37,
        protein: 26,
        sodium: 1020,
        ingredients: "Shrimp (Shrimp, Water, Salt), Cauliflower Cavatappi (Water, Cauliflower Powder, Potato Starch, Tapioca Starch, Whole Egg, Egg White, Xanthan Gum, Konjac, Salt), Broccoli, Cauliflower, Whole Milk (Pasteurized Milk, Vitamin D3), Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Onions, Garlic, Heavy Cream, Olive Pomace Oil, Grated Romano Cheese (Imported Romano (Sheep’S Milk, Cheese Culture, Salt, Enzymes), Powdered Cellulose (Anti-Caking Agent), And Calcium Propionate (Preservative)), Chardonnay Wine (Grapes, Sulfites), Grated Parmesan Cheese ((Parmesan Cheese (Pasteurized Cow’S Milk, Cheese Culture, Salt, Enzymes), Water, Milk Protein, Modified Food Starch, Palm Oil Blend, Salt, Disodium Phosphate, Citric Acid, Xanthan Gum), And Calcium Propionate (Preservative)), Toasted Garlic, Parsley, Sea Salt, Smoked Black Pepper (Pepper, Smoke Flavor), Green Onions, Black Pepper, Toasted Garlic Powder, Dried Chives\n",
        name: "Romano & Black Pepper Shrimp Pasta",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/6446a3fbd3e121d720036537-6ef6b7ba.jpg",
        prep_cook_time: 300
    },
    {
        calories: 580,
        fat: 28,
        carbohydrates: 69,
        protein: 19,
        sodium: 840,
        ingredients: "Yellow Sweet Corn, Tomatillos, Water, Shredded Pepper Jack Cheese ((Pasteurized Milk, Hot Peppers (Jalapeño Peppers, Habanero Peppers), Cheese Culture, Salt, Enzymes), Potato Starch And Powdered Cellulose (Anti-Caking Agents) Natamycin (A Natural Mold Inhibitor)), Black Beans (Prepared Black Beans, Water, Salt, And Calcium Chloride (Firming Agent)), Kidney Beans (Dark Red Kidney Beans, Water, Salt, Calcium Chloride (A Firming Agent) And/Or Disodium Edta (To Promote Color Retention)), Pinto Beans (Prepared Pinto Beans, Water, Salt, Calcium Chloride (Firming Agent), Calcium Disodium Edta (Promotes Color Retention), Corn Tostadas (Corn, Corn Oil And/Or Coconut Oil, Water, Salt, Lime), Jalapeño Peppers, Onions, Red Onions, Concentrated Crushed Tomatoes (Tomatoes, Salt, Citric Acid), Red Bell Peppers, Poblano Peppers, Sour Cream (Cultured Cream), Brown Jasmine Rice, Cilantro, Light Sour Cream (Cultured Cream, Skim Milk), Garlic, Olive Pomace Oil, Apple Cider Vinegar, Lime Juice Concentrate, Sea Salt, Cumin, Ancho Chile Powder, Brown Chipotle Chile Powder, Paprika (Paprika And Silicon Dioxide (Added To Make Free Flowing)), Chili Powder (Chili Pepper, Spices (Including Mustard), Salt, Garlic Powder), Dried Oregano, Coriander, Lime Powder (Citric Acid, Natural Lime Flavor)\n",
        name: "Vegetarian Green Chile Tostada Bake",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/63ab15f1cd9223af2e03ae7d-7e56b1f3.jpg",
        prep_cook_time: 240
    },
    {
        calories: 400,
        fat: 19,
        carbohydrates: 50,
        protein: 10,
        sodium: 870,
        ingredients: "Water, Mushrooms, Green Beans, Arborio Rice, Onions, Olive Pomace Oil, Garlic, Chardonnay Wine (Grapes, Sulfites), Mirepoix Concentrate (Water, Sea Salt, Vegetable Stock (Carrot, Celery And Onion Stocks), Carrot Stock, Tapioca Starch, Cabbage Juice Concentrate, Celery Stock, Onion Stock, Natural Flavors, Mushroom Stock, Tomato Paste), Leeks, Shallots, Nutritional Yeast Flakes (Dried Yeast, Niacin, Pyridoxine Hydrochloride (B6), Riboflavin, Thiamine Hydrochloride, (Thiamine), Folic Acid, Cobalamin (B12)), Cabernet Sauvignon Wine (Grapes, Sulfites), Sherry Wine (Grapes, Sulfites), Sea Salt, Parsley, Thyme, Tapioca Starch, Toasted Onion Powder, Porcini Mushroom Powder, Smoked Black Pepper (Pepper, Smoke Flavor), Granulated Garlic, Black Pepper\n",
        name: "Vegan Mushroom Marsala",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/644ff020faaad5532f030bc5-c940ced7.jpg",
        prep_cook_time: 150
    },
    {
        calories: 440,
        fat: 21,
        carbohydrates: 56,
        protein: 10,
        sodium: 700,
        ingredients: "Water, Arborio Rice, Red Bell Peppers, Zucchini, Grape Tomatoes, Pine Nuts, Crushed Tomatoes (Tomatoes, Tomato Puree, Salt, Citric Acid, Ascorbic Acid), Red Onions, Cabernet Sauvignon Wine (Grapes, Sulfites), Olive Pomace Oil, Nutritional Yeast Flakes (Dried Yeast, Niacin, Pyridoxine Hydrochloride (B6), Riboflavin, Thiamine Hydrochloride, (Thiamine), Folic Acid, Cobalamin (B12)), Sea Salt, Garlic, Basil, Black Pepper\n",
        name: "Tomato & Roasted Vegetable Risotto",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/64593ce835b9b262940ab675-8939fc94.jpg",
        prep_cook_time: 300
    },
    {
        calories: 570,
        fat: 27,
        carbohydrates: 52,
        protein: 32,
        sodium: 890,
        ingredients: "Smoked Five Spice Tofu (Whole Soybeans, Calcium Sulfate, Glucono Delta- Lactone (Gdl), Water, Gluten-Free Soy Sauce, Kosher Salt, Spices (Peppercorn, Cumin, Cinnamon, Clove, Aniseed, Coriander)), Shelled Edamame, Water, Green Beans, Mushrooms, Brown Basmati Rice, Green Bell Peppers, Red Bell Peppers, Toasted Sesame Oil, Almonds, Tamari (Water, Soybeans, Salt, Alcohol (To Preserve Freshness)), Red Onions, Rice Vinegar, Garlic, Ginger, Maple Syrup, Blue Agave Nectar, Green Onions, Orange Juice, Sesame Seeds, Sea Salt, Granulated Garlic, Granulated Onion, Ground Ginger, Cilantro, Toasted Sesame Seeds, Coconut Aminos (Organic Coconut Nectar, Organic Pure Coconut Blossom Sap, Natural Unrefined Sea Salt (Less Than 2%)), Toasted Garlic Powder, Toasted Onion Powder, Black Pepper, Gochugaru Chile Flakes, White Pepper, Xanthan Gum\n",
        name: "Smoked Tofu Almond Stir-Fry",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/642b275acf3deac0aa0d29a6-66b39ab7.jpg",
        prep_cook_time: 150
    },
    {
        calories: 600,
        fat: 33,
        carbohydrates: 55,
        protein: 23,
        sodium: 840,
        ingredients: "Red Lentil Fusilli (Water, Red Lentil Flour, Potato Starch, Tapioca Starch, Whole Egg, Egg White, Xanthan Gum, Salt), Onions, Spinach, Mushrooms, Whole Milk (Pasteurized Milk, Vitamin D3), Cream Cheese (Pasteurized Cultured Milk And Cream, Salt, Stabilizers (Xanthan Gum, Carob Bean Gum, Guar Gum)), Shredded Mozzarella And Provolone Cheese (Part-Skim Mozzarella Cheese (Pasteurized Park-Skim Milk, Cheese Cultures, Salt, Enzymes), Provolone Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes, Anti-Caking Agent (Potato Starch, Powdered Cellulose), Natamycin (A Natural Mold Inhibitor)), Olive Pomace Oil, Green Onions, Garlic, Date Syrup, Mirepoix Concentrate (Water, Sea Salt, Vegetable Stock (Carrot, Celery And Onion Stocks), Carrot Stock, Tapioca Starch, Cabbage Juice Concentrate, Celery Stock, Onion Stock, Natural Flavors, Mushroom Stock, Tomato Paste), Heavy Cream, Almonds, Grated Parmesan Cheese ((Parmesan Cheese (Pasteurized Cow’S Milk, Cheese Culture, Salt, Enzymes), Water, Milk Protein, Modified Food Starch, Palm Oil Blend, Salt, Disodium Phosphate, Citric Acid, Xanthan Gum), And Calcium Propionate (Preservative)), Kale, Toasted Onion Powder, Black Pepper, Sea Salt, Smoked Black Pepper (Pepper, Smoke Flavor), Granulated Garlic, Granulated Onion, Xanthan Gum\n",
        name: "French Onion & Mushroom Fusilli",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/french-onion-mushroom-fusilli-w05-01b9035a.jpg",
        prep_cook_time: 270
    },
    {
        calories: 400,
        fat: 17,
        carbohydrates: 29,
        protein: 33,
        sodium: 630,
        ingredients: "Italian Herb Chicken Breast (Chicken, Water, Olive Oil, Red Wine Vinegar, Sea Salt, Dehydrated Garlic, Dehydrated Onion, Dehydrated Parsley, Italian Herb Seasoning (Rosemary Leaves, Oregano Leaves, Basil Leaves, Marjoram Leaves, Thyme) Black Pepper), Green Beans, Yukon Gold Potatoes, Sour Cream (Cultured Cream), Garlic, Whole Milk (Pasteurized Milk, Vitamin D3), Olive Pomace Oil, Green Onions, Roasted Chicken Stock (Chicken Stock, Roasted Chicken Stock, Mirepoix Stock (Made Of Carrot, Celery And Onion Stocks, Dried Chicken Stock, Salt, Gelatin, Water, White Wine)), Unsalted Butter (Pasteurized Cream, Natural Flavorings), Sea Salt, Smoked Black Pepper (Pepper, Smoke Flavor), Thyme\n",
        name: "Roasted Garlic Chicken",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/64591280107e498f3c06636f-2d1a027b.jpg",
        prep_cook_time: 240
    },
    {
        calories: 470,
        fat: 21,
        carbohydrates: 51,
        protein: 24,
        sodium: 930,
        ingredients: "Ground Beef, Sweet Potatoes, Crushed Tomatoes (Tomatoes, Tomato Puree, Salt, Citric Acid, Ascorbic Acid), Yellow Sweet Corn, Black Beans (Prepared Black Beans, Water, Salt, And Calcium Chloride (Firming Agent)), Diced Green Chiles (Green Chile Peppers, Water, Salt, Citric Acid, Calcium Chloride), Poblano Peppers, Red Bell Peppers, Garlic, Onions, Water, Olive Pomace Oil, Cilantro, Jalapeño Peppers, Green Onions, Red Onions, Cotija Cheese (Pasteurized Whole Cow''s Milk, Salt, Enzymes And Culture), Roasted Chicken Stock (Chicken Stock, Roasted Chicken Stock, Mirepoix Stock (Made Of Carrot, Celery And Onion Stocks, Dried Chicken Stock, Salt, Gelatin, Water, White Wine)), Smoked Paprika, Cumin, Ancho Chile Powder, Guajillo Chile Powder, Sea Salt, Smoked Black Pepper (Pepper, Smoke Flavor), Dried Oregano, Brown Chipotle Chile Powder, Paprika (Paprika And Silicon Dioxide (Added To Make Free Flowing)), Chili Powder (Chili Pepper, Spices (Including Mustard), Salt, Garlic Powder)\n",
        name: "Fiery Beef & Black Bean Chili",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/640b6e49bc01ad5b270dd566-31ce119a.jpg",
        prep_cook_time: 300
    },
    {
        calories: 500,
        fat: 26,
        carbohydrates: 37,
        protein: 27,
        sodium: 890,
        ingredients: "Zucchini, Red Lentil Fusilli (Water, Red Lentil Flour, Potato Starch, Tapioca Starch, Whole Egg, Egg White, Xanthan Gum, Salt), Chicken Breast, Spinach, Heavy Cream, Whole Milk (Pasteurized Milk, Vitamin D3), Water, Red Onions, Onions, Grated Parmesan Cheese ((Parmesan Cheese (Pasteurized Cow’S Milk, Cheese Culture, Salt, Enzymes), Water, Milk Protein, Modified Food Starch, Palm Oil Blend, Salt, Disodium Phosphate, Citric Acid, Xanthan Gum), And Calcium Propionate (Preservative)), Garlic, Olive Pomace Oil, Sun-Dried Tomatoes (Sun-Dried Tomatoes, Salt), Shredded Parmesan Cheese (Parmesan Cheese (Pasteurized Part-Skim Milk, Cheese Culture, Salt, Enzymes), Powdered Cellulose To Prevent Caking, Natamycin (A Natural Mold Inhibitor)), Red Wine Vinegar, Basil, Mirepoix Concentrate (Water, Sea Salt, Vegetable Stock (Carrot, Celery And Onion Stocks), Carrot Stock, Tapioca Starch, Cabbage Juice Concentrate, Celery Stock, Onion Stock, Natural Flavors, Mushroom Stock, Tomato Paste), Tomato Paste (Tomatoes, Citric Acid), Granulated Garlic, Toasted Onion Powder, Sea Salt, Dried Oregano, Smoked Black Pepper (Pepper, Smoke Flavor), Parsley, Italian Seasoning (Rosemary Leaves, Oregano Leaves, Basil Leaves, Marjoram Leaves, Thyme), Dried Basil, Granulated Onion, Crushed Red Pepper Flakes, Black Pepper\n",
        name: "Sun-Dried Tomato Chicken Fusilli",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/645918feb0c27eaa8b0ac4c7-c82afd82.jpg",
        prep_cook_time: 300
    },
    {
        calories: 450,
        fat: 14,
        carbohydrates: 44,
        protein: 33,
        sodium: 820,
        ingredients: "Chicken Breast, Water, Broccoli, Brown Jasmine Rice, Chardonnay Wine (Grapes, Sulfites), Green Onions, Red Bell Peppers, Pineapple, Coconut Sugar, Pineapple, Tamari (Water, Soybeans, Salt, Alcohol (To Preserve Freshness)), Garlic, Red Miso Paste (Filtered Water, Cultured Rice, Organic Whole Soybeans, Sea Salt), Unsweetened Shredded Coconut, Olive Pomace Oil, Toasted Sesame Oil, Rice Vinegar, Ginger, Toasted Sesame Seeds, Sea Salt, Dried Onion Flakes, Black Sesame Seeds, Gochugaru Chile Flakes, Granulated Garlic\n",
        name: "Hawaiian-Style Shredded Chicken",
        image_url: "https://images.everyplate.com/c_fill,f_auto,fl_lossy,h_625,q_auto,w_1230/everyplate_s3/image/649f03871f082ea3565720e1-863e239a.jpeg",
        prep_cook_time: 120
    },
    {
        calories: 600,
        fat: 33,
        carbohydrates: 28,
        protein: 51,
        sodium: 1620,
        ingredients: "Brussels Sprouts, Cream cheese, Butter, Roasted Red Pepper, Boneless Skinless Chicken Breasts, Shredded Asiago cheese, Panko Breadcrumbs, Honey, Red Pepper flakes",
        name: "Cheesy Red Pepper-Stuffed Chicken",
        image_url: "https://homechef.imgix.net/https%3A%2F%2Fasset.homechef.com%2Fuploads%2Fmeal%2Fplated%2F24750%2F729207.001.01CheesyRedPepperStuffedChicken_R_D_4_of_7_.jpg?ixlib=rails-1.1.0&w=850&auto=format&s=16a4e09abb86c9b8d20e74c74d04fb71",
        prep_cook_time: 300
    },
    // {
    //     calories: 670,
    //     fat: 37,
    //     carbohydrates: 50,
    //     protein: 36,
    //     sodium: 1530,
    //     ingredients: "Steak strips, Cremenini Mushrooms, Sour Cream, Crispy Fried Onions, Flour Tortillas, Cream Cheese, Green onions, Beef flavor demi-glaze concentrate",
    //     name: "Fiesta Steak and Mushroom Flautas",
    //     image_url: "https://homechef.imgix.net/https%3A%2F%2Fasset.homechef.com%2Fuploads%2Fmeal%2Fplated%2F29168%2F359286.024.01FiestaSteakAndMushroomFlautas_Ecomm_3_of_5_-01-19-23-161159.jpg?ixlib=rails-1.1.0&w=425&auto=format&s=97994b787dec6a8dc32d564a7fe77b08",
    //     prep_cook_time: 270
    // }
]